### ISSUE TITLE
after enter my apple account info get an error

### ISSUE THREAD

**Issue by hugoerg56** [HipByte/motion-provisioning#14]
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

```
SL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
rake aborted!
Spaceship::Client::AppleTimeoutError: Could not receive latest API key from iTunes Connect, this might be a server issue.
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/spaceship-0.39.0/lib/spaceship/client.rb:354:in `rescue in itc_service_key'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/spaceship-0.39.0/lib/spaceship/client.rb:331:in `itc_service_key'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/spaceship-0.39.0/lib/spaceship/client.rb:294:in `block in send_shared_login_request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/connection.rb:374:in `block in run_request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/connection.rb:388:in `block in build_request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/request.rb:26:in `block in create'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/request.rb:25:in `tap'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/request.rb:25:in `create'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/connection.rb:384:in `build_request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/connection.rb:370:in `run_request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/connection.rb:177:in `post'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/spaceship-0.39.0/lib/spaceship/client.rb:464:in `block in send_request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/spaceship-0.39.0/lib/spaceship/client.rb:362:in `with_retry'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/spaceship-0.39.0/lib/spaceship/client.rb:463:in `send_request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/spaceship-0.39.0/lib/spaceship/client.rb:400:in `request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/spaceship-0.39.0/lib/spaceship/client.rb:293:in `send_shared_login_request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/spaceship-0.39.0/lib/spaceship/portal/portal_client.rb:13:in `send_login_request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/spaceship-0.39.0/lib/spaceship/client.rb:430:in `do_login'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/motion-provisioning-0.0.7/lib/motion-provisioning.rb:69:in `client'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/motion-provisioning-0.0.7/lib/motion-provisioning/certificate.rb:6:in `client'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/motion-provisioning-0.0.7/lib/motion-provisioning/certificate.rb:39:in `certificate_name'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/motion-provisioning-0.0.7/lib/motion-provisioning.rb:206:in `certificate'
/Users/hugorincon/Trabajo/CCConnect/curbcall/Rakefile:51:in `block (2 levels) in <top (required)>'
/Library/RubyMotion/lib/motion/project/config.rb:202:in `development'
/Users/hugorincon/Trabajo/CCConnect/curbcall/Rakefile:50:in `block in <top (required)>'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/bubble-wrap-1.9.6/lib/bubble-wrap/ext/motion_project_app.rb:10:in `call'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/bubble-wrap-1.9.6/lib/bubble-wrap/ext/motion_project_app.rb:10:in `block in setup_with_bubblewrap'
/Library/RubyMotion/lib/motion/project/config.rb:121:in `call'
/Library/RubyMotion/lib/motion/project/config.rb:121:in `block in setup'
/Library/RubyMotion/lib/motion/project/config.rb:121:in `each'
/Library/RubyMotion/lib/motion/project/config.rb:121:in `setup'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/sugarcube-3.3.7/lib/sugarcube_pre_setup.rb:37:in `setup'
/Library/RubyMotion/lib/motion/project/app.rb:66:in `config'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/bubble-wrap-1.9.6/lib/bubble-wrap/ext/motion_project_app.rb:24:in `config_with_bubblewrap'
/Library/RubyMotion/lib/motion/project/template/ios.rb:157:in `block in <top (required)>'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/bin/ruby_executable_hooks:15:in `eval'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/bin/ruby_executable_hooks:15:in `<main>'
Faraday::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/adapter/net_http.rb:81:in `perform_request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/adapter/net_http.rb:41:in `block in call'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/adapter/net_http.rb:88:in `with_net_http_connection'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/adapter/net_http.rb:33:in `call'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-cookie_jar-0.0.6/lib/faraday/cookie_jar.rb:22:in `call'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday_middleware-0.10.1/lib/faraday_middleware/response_middleware.rb:30:in `call'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday_middleware-0.10.1/lib/faraday_middleware/response_middleware.rb:30:in `call'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday_middleware-0.10.1/lib/faraday_middleware/response_middleware.rb:30:in `call'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/rack_builder.rb:139:in `build_response'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/connection.rb:377:in `run_request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/connection.rb:140:in `get'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/spaceship-0.39.0/lib/spaceship/client.rb:464:in `block in send_request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/spaceship-0.39.0/lib/spaceship/client.rb:362:in `with_retry'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/spaceship-0.39.0/lib/spaceship/client.rb:463:in `send_request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/spaceship-0.39.0/lib/spaceship/client.rb:400:in `request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/spaceship-0.39.0/lib/spaceship/client.rb:345:in `itc_service_key'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/spaceship-0.39.0/lib/spaceship/client.rb:294:in `block in send_shared_login_request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/connection.rb:374:in `block in run_request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/connection.rb:388:in `block in build_request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/request.rb:26:in `block in create'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/request.rb:25:in `tap'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/request.rb:25:in `create'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/connection.rb:384:in `build_request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/connection.rb:370:in `run_request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/connection.rb:177:in `post'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/spaceship-0.39.0/lib/spaceship/client.rb:464:in `block in send_request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/spaceship-0.39.0/lib/spaceship/client.rb:362:in `with_retry'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/spaceship-0.39.0/lib/spaceship/client.rb:463:in `send_request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/spaceship-0.39.0/lib/spaceship/client.rb:400:in `request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/spaceship-0.39.0/lib/spaceship/client.rb:293:in `send_shared_login_request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/spaceship-0.39.0/lib/spaceship/portal/portal_client.rb:13:in `send_login_request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/spaceship-0.39.0/lib/spaceship/client.rb:430:in `do_login'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/motion-provisioning-0.0.7/lib/motion-provisioning.rb:69:in `client'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/motion-provisioning-0.0.7/lib/motion-provisioning/certificate.rb:6:in `client'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/motion-provisioning-0.0.7/lib/motion-provisioning/certificate.rb:39:in `certificate_name'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/motion-provisioning-0.0.7/lib/motion-provisioning.rb:206:in `certificate'
/Users/hugorincon/Trabajo/CCConnect/curbcall/Rakefile:51:in `block (2 levels) in <top (required)>'
/Library/RubyMotion/lib/motion/project/config.rb:202:in `development'
/Users/hugorincon/Trabajo/CCConnect/curbcall/Rakefile:50:in `block in <top (required)>'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/bubble-wrap-1.9.6/lib/bubble-wrap/ext/motion_project_app.rb:10:in `call'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/bubble-wrap-1.9.6/lib/bubble-wrap/ext/motion_project_app.rb:10:in `block in setup_with_bubblewrap'
/Library/RubyMotion/lib/motion/project/config.rb:121:in `call'
/Library/RubyMotion/lib/motion/project/config.rb:121:in `block in setup'
/Library/RubyMotion/lib/motion/project/config.rb:121:in `each'
/Library/RubyMotion/lib/motion/project/config.rb:121:in `setup'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/sugarcube-3.3.7/lib/sugarcube_pre_setup.rb:37:in `setup'
/Library/RubyMotion/lib/motion/project/app.rb:66:in `config'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/bubble-wrap-1.9.6/lib/bubble-wrap/ext/motion_project_app.rb:24:in `config_with_bubblewrap'
/Library/RubyMotion/lib/motion/project/template/ios.rb:157:in `block in <top (required)>'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/bin/ruby_executable_hooks:15:in `eval'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/bin/ruby_executable_hooks:15:in `<main>'
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/adapter/net_http.rb:81:in `perform_request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/adapter/net_http.rb:41:in `block in call'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/adapter/net_http.rb:88:in `with_net_http_connection'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/adapter/net_http.rb:33:in `call'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-cookie_jar-0.0.6/lib/faraday/cookie_jar.rb:22:in `call'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday_middleware-0.10.1/lib/faraday_middleware/response_middleware.rb:30:in `call'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday_middleware-0.10.1/lib/faraday_middleware/response_middleware.rb:30:in `call'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday_middleware-0.10.1/lib/faraday_middleware/response_middleware.rb:30:in `call'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/rack_builder.rb:139:in `build_response'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/connection.rb:377:in `run_request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/connection.rb:140:in `get'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/spaceship-0.39.0/lib/spaceship/client.rb:464:in `block in send_request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/spaceship-0.39.0/lib/spaceship/client.rb:362:in `with_retry'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/spaceship-0.39.0/lib/spaceship/client.rb:463:in `send_request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/spaceship-0.39.0/lib/spaceship/client.rb:400:in `request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/spaceship-0.39.0/lib/spaceship/client.rb:345:in `itc_service_key'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/spaceship-0.39.0/lib/spaceship/client.rb:294:in `block in send_shared_login_request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/connection.rb:374:in `block in run_request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/connection.rb:388:in `block in build_request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/request.rb:26:in `block in create'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/request.rb:25:in `tap'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/request.rb:25:in `create'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/connection.rb:384:in `build_request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/connection.rb:370:in `run_request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/faraday-0.10.0/lib/faraday/connection.rb:177:in `post'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/spaceship-0.39.0/lib/spaceship/client.rb:464:in `block in send_request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/spaceship-0.39.0/lib/spaceship/client.rb:362:in `with_retry'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/spaceship-0.39.0/lib/spaceship/client.rb:463:in `send_request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/spaceship-0.39.0/lib/spaceship/client.rb:400:in `request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/spaceship-0.39.0/lib/spaceship/client.rb:293:in `send_shared_login_request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/spaceship-0.39.0/lib/spaceship/portal/portal_client.rb:13:in `send_login_request'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/spaceship-0.39.0/lib/spaceship/client.rb:430:in `do_login'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/motion-provisioning-0.0.7/lib/motion-provisioning.rb:69:in `client'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/motion-provisioning-0.0.7/lib/motion-provisioning/certificate.rb:6:in `client'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/motion-provisioning-0.0.7/lib/motion-provisioning/certificate.rb:39:in `certificate_name'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/motion-provisioning-0.0.7/lib/motion-provisioning.rb:206:in `certificate'
/Users/hugorincon/Trabajo/CCConnect/curbcall/Rakefile:51:in `block (2 levels) in <top (required)>'
/Library/RubyMotion/lib/motion/project/config.rb:202:in `development'
/Users/hugorincon/Trabajo/CCConnect/curbcall/Rakefile:50:in `block in <top (required)>'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/bubble-wrap-1.9.6/lib/bubble-wrap/ext/motion_project_app.rb:10:in `call'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/bubble-wrap-1.9.6/lib/bubble-wrap/ext/motion_project_app.rb:10:in `block in setup_with_bubblewrap'
/Library/RubyMotion/lib/motion/project/config.rb:121:in `call'
/Library/RubyMotion/lib/motion/project/config.rb:121:in `block in setup'
/Library/RubyMotion/lib/motion/project/config.rb:121:in `each'
/Library/RubyMotion/lib/motion/project/config.rb:121:in `setup'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/sugarcube-3.3.7/lib/sugarcube_pre_setup.rb:37:in `setup'
/Library/RubyMotion/lib/motion/project/app.rb:66:in `config'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/bubble-wrap-1.9.6/lib/bubble-wrap/ext/motion_project_app.rb:24:in `config_with_bubblewrap'
/Library/RubyMotion/lib/motion/project/template/ios.rb:157:in `block in <top (required)>'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/bin/ruby_executable_hooks:15:in `eval'
/Users/hugorincon/.rvm/gems/ruby-2.2.2@ccconnect/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by abaroody** [comment]
I had this problem too and seemed to solve it with reinstalling Ruby from source using:

`rvm reinstall 2.2.3 --disable-binary`

Found this solution on stackoverflow at [SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed](http://stackoverflow.com/questions/4528101/ssl-connect-returned-1-errno-0-state-sslv3-read-server-certificate-b-certificat#5973759) and [Can't run Ruby 2.2.3 with RVM on OSX](http://stackoverflow.com/questions/32353917/cant-run-ruby-2-2-3-with-rvm-on-osx/32363597#32363597).

**Comment by andrewhavens** [comment]
Try again with version 1.0.0.
