### ISSUE TITLE
Doesn't handle updated license not agreed

### ISSUE THREAD

**Issue by jjaffeux** [HipByte/motion-provisioning#3]
```
Spaceship::Client::UnexpectedResponse: {"responseId"=>"5068aec2-d34d-4bdd-a998-d8f3d777b073", "resultCode"=>4550, "resultString"=>"Program License Agreement updated", "userString"=>"The selected team&#x27;s agent, &#x27;xxxx xxxx&#x27; must agree to the latest Program License Agreement in their developer account.&#xa;https&#x3a;&#x2f;&#x2f;developer.apple.com&#x2f;account&#x2f;", "creationTimestamp"=>"2016-08-14T15:07:35Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developer.apple.com/services-account/QH65B2/account/ios/identifiers/listAppIds.action", "httpCode"=>200}
/Users/joffreyjaffeux/.gem/ruby/2.3.1/gems/spaceship-0.31.1/lib/spaceship/client.rb:433:in `parse_response'
/Users/joffreyjaffeux/.gem/ruby/2.3.1/gems/spaceship-0.31.1/lib/spaceship/portal/portal_client.rb:115:in `block in apps'
/Users/joffreyjaffeux/.gem/ruby/2.3.1/gems/spaceship-0.31.1/lib/spaceship/client.rb:182:in `block in paging'
/Users/joffreyjaffeux/.gem/ruby/2.3.1/gems/spaceship-0.31.1/lib/spaceship/client.rb:180:in `loop'
/Users/joffreyjaffeux/.gem/ruby/2.3.1/gems/spaceship-0.31.1/lib/spaceship/client.rb:180:in `paging'
/Users/joffreyjaffeux/.gem/ruby/2.3.1/gems/spaceship-0.31.1/lib/spaceship/portal/portal_client.rb:108:in `apps'
/Users/joffreyjaffeux/.gem/ruby/2.3.1/gems/spaceship-0.31.1/lib/spaceship/portal/app.rb:80:in `all'
/Users/joffreyjaffeux/.gem/ruby/2.3.1/gems/spaceship-0.31.1/lib/spaceship/portal/app.rb:105:in `find'
/Users/joffreyjaffeux/.gem/ruby/2.3.1/gems/motion-provisioning-0.0.3/lib/motion-provisioning/application.rb:6:in `find_or_create'
/Users/joffreyjaffeux/.gem/ruby/2.3.1/gems/motion-provisioning-0.0.3/lib/motion-provisioning/provisioning_profile.rb:38:in `provisioning_profile'
/Users/joffreyjaffeux/.gem/ruby/2.3.1/gems/motion-provisioning-0.0.3/lib/motion-provisioning.rb:227:in `profile'
/Users/joffreyjaffeux/Documents/projects/ColorGolfMobile/config/ios.rb:19:in `block (2 levels) in <top (required)>'
/Library/RubyMotion/lib/motion/project/config.rb:202:in `development'
/Users/joffreyjaffeux/Documents/projects/ColorGolfMobile/config/ios.rb:14:in `block in <top (required)>'
/Library/RubyMotion/lib/motion/project/config.rb:121:in `block in setup'
/Library/RubyMotion/lib/motion/project/config.rb:121:in `each'
/Library/RubyMotion/lib/motion/project/config.rb:121:in `setup'
/Library/RubyMotion/lib/motion/project/app.rb:66:in `config'
/Library/RubyMotion/lib/motion/project/template/ios.rb:157:in `block in <top (required)>'
/Users/joffreyjaffeux/.gem/ruby/2.3.1/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => simulator
(See full trace by running task with --trace)
```

**Comment by andrewhavens** [comment]
Try again with version 1.0.0.
