### ISSUE TITLE
Two-step verification not supported

### ISSUE THREAD

**Issue by caramdache** [HipByte/motion-provisioning#9]
Hey Mark,

Excellent work! but could it be that 2-step verification is not supported?

```
Two Step Verification for account 'xxxx@yyy.com' is enabled
Please select a device to verify your identity
rake aborted!
NoMethodError: undefined method`choose' for #Spaceship::PortalClient:0x007fe8eee43868
/usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.34.1/lib/spaceship/two_step_client.rb:35:in `handle_two_step'
/usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.34.1/lib/spaceship/client.rb:297:in`send_shared_login_request'
/usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.34.1/lib/spaceship/portal/portal_client.rb:13:in `send_login_request'
/usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.34.1/lib/spaceship/client.rb:372:in`do_login'
/usr/local/lib/ruby/gems/2.2.0/gems/motion-provisioning-0.0.5/lib/motion-provisioning.rb:68:in `client'
/usr/local/lib/ruby/gems/2.2.0/gems/motion-provisioning-0.0.5/lib/motion-provisioning/certificate.rb:6:in`client'
/usr/local/lib/ruby/gems/2.2.0/gems/motion-provisioning-0.0.5/lib/motion-provisioning/certificate.rb:42:in `certificate_name'
/usr/local/lib/ruby/gems/2.2.0/gems/motion-provisioning-0.0.5/lib/motion-provisioning.rb:195:in`certificate'
/Users/jj/Source/tarot/Rakefile:45:in `block (2 levels) in <top (required)>'
/Library/RubyMotion/lib/motion/project/config.rb:202:in`development'
/Users/jj/Source/tarot/Rakefile:42:in `block in <top (required)>'
/Library/RubyMotion/lib/motion/project/config.rb:121:in`call'
/Library/RubyMotion/lib/motion/project/config.rb:121:in `block in setup'
/Library/RubyMotion/lib/motion/project/config.rb:121:in`each'
/Library/RubyMotion/lib/motion/project/config.rb:121:in `setup'
/Library/RubyMotion/lib/motion/project/app.rb:66:in`config'
/Library/RubyMotion/lib/motion/project/template/ios.rb:157:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.2.0/gems/rake-11.3.0/exe/rake:27:in`<top (required)>'
```

**Comment by andrewtimberlake** [comment]
This is now a problem for me as well.

**Comment by abaroody** [comment]
I was able to fix the two-factor issue by changing the gem dependency of motion-provisioning from spaceship to fastlane and following the 2 Step Verification instructions at [https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification](https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification).

My fork of motion-provisioning with the gem change is at abaroody/motion-provisioning.

The error that this fixed for me was "Invalid 2 step response" but it might help with this issue as well.
